### ISSUE TITLE
Support for Rails 7

### ISSUE THREAD

**Issue by montulli** [fishbrain/administrate-field-belongs_to_search#106]
The gem appears to work fine with Rails 7.  Is there any reason for the restriction of less than rails 7?

**Comment by KjellMorgenstern** [comment]
The restriction was already lifted with pull request #105 . But it seems rubygems.org doesn't have the change yet. Probably the gem version needs to be lifted as well for rubygems to pick it up.

**Comment by kaderate** [comment]
A new release would be appreciated.

**Comment by rmachielse** [comment]
Same here, a release would be appreciated @klaseskilson @tim-heighes-fishbrain 🙏

**Comment by rmachielse** [comment]
Maybe @dalen or @pastpatryk is able to help us? 🙏 🙏

**Comment by alexceder** [comment]
I have release a new version. however, you will have to forgive me, but I have not 100 % verified myself that it is working properly. but I hope it is working for y'all.

full disclosure: we don't actively use administrate as of 2019 at Fishbrain.

**Comment by rmachielse** [comment]
@alexceder thank you so much! Judging from [the diff](https://github.com/fishbrain/administrate-field-belongs_to_search/compare/v0.7.0...v0.8.0), the changes shouldn't include much more than allowing Rails 7.0, so it should be fine 💪
