### ISSUE TITLE
gemspec dependencies are too tight

### ISSUE THREAD

**Issue by dan-ding** [fishbrain/administrate-field-belongs_to_search#11]
like rails (5.1.2) and administrate (0.8.1)

**Comment by klaseskilson** [comment]
Hey @dan-ding, I'm currently unable to look at this in the immediate future. Care to provide a PR? I might have some time this weekend, but I cannot promise anything.

(Or perhaps if @Niklas9 knows someone who could jump in on this?)

**Comment by Niklas9** [comment]
Nothing immediate, sorry

**Comment by klaseskilson** [comment]
Version 0.4.0 was just released, fixing this. Again, thanks @dan-ding!
