### ISSUE TITLE
Search by belongs_to record attribute

### ISSUE THREAD

**Issue by varg90** [fishbrain/administrate-field-belongs_to_search#13]
Hi there!
I'm trying to use this gem for my case:
I have a `projects`, `users` and many-to-many `project_users`. When I'm on the `Project Users` admin page I want to be able to search `project_user` by its `project` title (or `user` email, for example). 
In `project_dashboard` I changed `display_resource` to use the title and added this to `project_user_dashboard`:
```
ATTRIBUTE_TYPES = {
  ...
  project: Field::BelongsToSearch.with_options(class_name: 'Project', searchable: true),
  ...
```
As you might guess, I got
```
PG::UndefinedColumn: ERROR:  column project_users.project does not exist 
. . . 
WHERE (lower("project_users"."project") LIKE '%something%')
. . .
```
Could you give me any advise how to change this `ATTRIBUTE_TYPES` key (`project`) to search by its title?
Is it exactly that this gem should provide, or I use it wrong?
Thanks

**Comment by varg90** [comment]
I didn't point the details:
I use:
`administrate (0.8.1)`
`administrate-field-belongs_to_search (0.4.0)`
`rails 5.1.4`
`ruby 2.4.1`

**Comment by klaseskilson** [comment]
Hmm. If I understand you correctly, what you want to do is to use this gem to extend Administrate's search capabilities. Am I correct there?

If so, I'm sorry to tell you that this isn't really the purpose of this gem. What is provided here is a way of replacing the regular drop down that is used to _edit_ a `belongs_to` relationship with a search box.

**Comment by varg90** [comment]
Ah, I see. You totally correct. Thanks for your answer!

**Comment by klaseskilson** [comment]
Thank you! I'll see if there's some updates I can make to the description to make this more obvious. 👍
