### ISSUE TITLE
jbuilder should be listed in dependencies

### ISSUE THREAD

**Issue by such** [fishbrain/administrate-field-belongs_to_search#15]
Hello,
Thanks a lot for your plugin!
I think `jbuilder` should be listed as a dependency since it's used in the `administrate/application/index.json.jbuilder` template. If the rails project does not use jbuilder then the template is not found and it results in a `Missing template` error.

**Comment by klaseskilson** [comment]
Hey @such! Thanks for the issue. I definitely agree, will update and release 0.6.0. immediately.
