### ISSUE TITLE
Search records gives cached 304 response

### ISSUE THREAD

**Issue by StarWar** [fishbrain/administrate-field-belongs_to_search#24]
My rails 5.2 app, I am using acts_as_taggable_on and have following
``` ruby
ATTRIBUTE_TYPES = {
      tag:        Field::BelongsToSearch.with_options(class_name: '::ActsAsTaggableOn::Tag', searchable: true, searchable_field: :name),
      taggable:   Field::Polymorphic,
      tagger:     Field::Polymorphic,
      id:         Field::Number,
      tag_id:     Field::Number.with_options(searchable: false),
      context:    Field::Select.with_options(collection: ActsAsTaggableOn::Tagging.select(:context).uniq.map(&:context).uniq),
      created_at: Field::DateTime
    }.freeze
```
And I have following form
``` ruby
FORM_ATTRIBUTES = %i[
      tag
      context
    ].freeze
```
And it doesn't search and returns the cached response. In the network tab of chrome, I see only 304 responses no matter what the query is and it doesn't give the result from the search.

**Comment by klaseskilson** [comment]
Hey @StarWar,

Thanks for the issue. Do you have access to the Rails console for your app? Is it possible that it might give you some hints on why Rails returns 304?

**Comment by klaseskilson** [comment]
Needs more info. Feel free to reopen.
