### ISSUE TITLE
Add BelongsToSearch in Nested form

### ISSUE THREAD

**Issue by bilal14079** [fishbrain/administrate-field-belongs_to_search#32]
Hello guys! I hope everybody is doing great.
I'm facing problem to add belongs_to search from "administrate-field-belongs_to_search" in dropdown of nested forms.
As you can see in attachment, order_items is nested form for new order and I need to add search on its product dropdown.
Waiting for your help.

![image](https://user-images.githubusercontent.com/42926211/55797274-7052dc80-5ae5-11e9-854c-9afd2ed16456.png)

**Comment by klaseskilson** [comment]
What happens when you try and use it? Is this nested form an Administrate feature?

**Comment by klaseskilson** [comment]
Need more info.

**Comment by nunesmatheus** [comment]
I know it's late, but for future reference, [here](https://github.com/nickcharlton/administrate-field-nested_has_many/issues/22) is how this can be solved.
