### ISSUE TITLE
Partial Population for Belongs to Search

### ISSUE THREAD

**Issue by timchipperfield** [fishbrain/administrate-field-belongs_to_search#41]
## Describe the bug
The search field is not populating all of the Users. Instead it's only showing a small percentage of Users available for a belongs_to association.

## To Reproduce
Steps to reproduce the behaviour:

Click on new record and start typing in the belongs_to field and view the pre-populated records (in my case, Users). Many (or most) of the records are missing.

If I type out a user is ex (User #287), if it was not one of the pre-populated users, it will fail to create the record, even while the User # 287 does exist in the database is is findable via the User administrate dashboard.

## Environment

ruby "2.5.1"
rails "5.2.2.1"

Gemfile:
gem "administrate", "~> 0.11"
gem "administrate_exportable"

## Expected behavior
I would expect a pre-populated list containing all of the records and if the record is not showing up, I should still be able to type it in and find it.

## Additional context**

Dashboard Configuration:  
```
ATTRIBUTE_TYPES = {
    user:          Field::BelongsToSearch.with_options(class_name: "User"),
    tos_agreement: Field::BelongsTo,
    id:            Field::Number.with_options(searchable: true),
    created_at:    Field::DateTime,
    updated_at:    Field::DateTime
  }.freeze
```

Screen Shots:

Search finds incomplete list of users. Should be sequential users:
![Screen Shot 2019-06-28 at 2 39 52 PM](https://user-images.githubusercontent.com/17764313/60373547-69858880-99b5-11e9-82eb-100b6deb0d3e.png)

Error when User #287 which wasn't showing up in the list manually written in and then searched.
![Screen Shot 2019-06-28 at 2 45 34 PM](https://user-images.githubusercontent.com/17764313/60373554-6ee2d300-99b5-11e9-8347-d5a38669f0b6.png)

**Comment by klaseskilson** [comment]
Hey, thanks for dropping by!

The way this gem works is that it is simply adding a [new json view template](https://github.com/fishbrain/administrate-field-belongs_to_search/blob/240a7bfdde95a405a1c82822a3c9bf8dcfc04d35/app/views/administrate/application/index.json.jbuilder) to what is available, and relying on the querying logic in your dashboard's regular table view. So if you have modified your Users dashboard to only allow some users to appear, only those users will show in this search field.

Please check the controller for the Users if there are any `where` rules defined there. Perhaps there is an interfering scope as well?

**Comment by klaseskilson** [comment]
Feel free to get back on this. I do not think the issue lies inside the Gem here.
